# Generated by Django 4.0.1 on 2022-01-29 21:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False, unique=True)),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('priority', models.CharField(choices=[('UNKNOWN', 'Unknown'), ('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High')], default='UNKNOWN', max_length=10)),
            ],
        ),
    ]
